#!/usr/bin/env python3

import shutil
import argparse
import subprocess

class settings:
    script = None
    path = None

def arguments():
    parser = argparse.ArgumentParser(description = 'Automated script installer')
    parser.add_argument('-s', '--script', help = "Script to install", required = True)
    parser.add_argument('-p', '--path',   help = "Where the script will be installed", default = "/usr/bin/", required = True)
    settings.script = parser.parse_args().script
    settings.path = parser.parse_args().path

def clean():
    if settings.path.endswith("/") ==  False:
        settings.path += "/"

def main():
    arguments()
    if settings.script != None and settings.path != None:
        clean()
        try:
            shutil.copyfile(settings.script, "%s%s" % (settings.path, settings.script))
            subprocess.run(["chmod", "+x", "%s%s" % (settings.path, settings.script)])
            print("Copied !")
        except:
            print("Permission denied")


main()